In [7]:
import torch
# Создайте следующие тензоры:
print(torch.rand(3,4))# - Тензор размером 3x4, заполненный случайными числами от 0 до 1
print(torch.zeros(2,3,4))# - Тензор размером 2x3x4, заполненный нулями
print(torch.ones(5,5))# - Тензор размером 5x5, заполненный единицами
print(torch.reshape(torch.arange(0,16),(4,4)))# - Тензор размером 4x4 с числами от 0 до 15 (используйте reshape)

tensor([[0.0804, 0.8904, 0.0171, 0.6562],
        [0.8071, 0.8147, 0.5322, 0.5636],
        [0.2124, 0.6340, 0.4429, 0.2169]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])


In [14]:
A = torch.rand(3,4)# Дано: тензор A размером 3x4 и тензор B размером 4x3
B = torch.rand(4,3)
# Выполните:
print(A.T)# - Транспонирование тензора A
print(A@B)# - Матричное умножение A и B
print(A*B.T)# - Поэлементное умножение A и транспонированного B
print(torch.sum(A))# - Вычислите сумму всех элементов тензора A

tensor([[6.1758e-01, 3.1989e-01, 7.0802e-01],
        [4.8949e-01, 3.7930e-01, 4.2642e-01],
        [9.9727e-01, 7.7963e-05, 4.6058e-01],
        [5.2383e-02, 2.6721e-04, 5.3277e-01]])
tensor([[1.0895, 0.7789, 1.2770],
        [0.2624, 0.4020, 0.3270],
        [0.7798, 0.8089, 0.8331]])
tensor([[1.2906e-01, 2.5227e-01, 6.9938e-01, 8.7532e-03],
        [5.9035e-02, 3.4284e-01, 1.5861e-05, 9.9845e-05],
        [8.8887e-02, 3.2242e-01, 3.8119e-01, 4.0586e-02]])
tensor(4.9841)


In [46]:
A = torch.reshape(torch.arange(125),(5,5,5))# Создайте тензор размером 5x5x5
# Извлеките:
print(A[0,0,:])# - Первую строку
print(A[-1,:,-1])# - Последний столбец
print(A[2,1:3,1:3])# - Подматрицу размером 2x2 из центра тензора
print(A[::2,::2,::2])# - Все элементы с четными индексами

tensor([0, 1, 2, 3, 4])
tensor([104, 109, 114, 119, 124])
tensor([[56, 57],
        [61, 62]])
tensor([[[  0,   2,   4],
         [ 10,  12,  14],
         [ 20,  22,  24]],

        [[ 50,  52,  54],
         [ 60,  62,  64],
         [ 70,  72,  74]],

        [[100, 102, 104],
         [110, 112, 114],
         [120, 122, 124]]])


In [50]:
A = torch.arange(24)# Создайте тензор размером 24 элемента
# Преобразуйте его в формы:
print(A.reshape(2,12))# - 2x12
print(A.reshape(3,8))# - 3x8
print(A.reshape(4,6))# - 4x6
print(A.reshape(2,3,4))# - 2x3x4
print(A.reshape(2,2,2,3))# - 2x2x2x3

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor([[[[ 0,  1,  2],
          [ 3,  4,  5]],

         [[ 6,  7,  8],
          [ 9, 10, 11]]],


        [[[12, 13, 14],
          [15, 16, 17]],

         [[18, 19, 20],
          [21, 22, 23]]]])
