In [16]:
import torch
x,y,z = torch.rand((5,5),requires_grad=True),torch.rand((5,5),requires_grad=True),torch.rand((5,5),requires_grad=True)# Создайте тензоры x, y, z с requires_grad=True
f = x**2 + y**2 + z**2 + 2*x*y*z# Вычислите функцию: f(x,y,z) = x^2 + y^2 + z^2 + 2*x*y*z
print(f,'\n')
f = f.sum()
f.backward()
print(x.grad,'\n',y.grad,'\n',z.grad,'\n')# Найдите градиенты по всем переменным
print(2*x+2*y*z)# Проверьте результат аналитически - сходится

tensor([[0.3530, 1.5456, 1.5415, 0.8965, 1.6966],
        [1.0458, 0.8982, 1.3597, 1.7520, 0.7954],
        [1.3357, 0.7506, 2.3759, 1.3431, 1.5969],
        [0.8305, 1.2987, 2.2019, 1.7287, 1.6127],
        [3.6202, 1.2584, 0.8947, 1.6503, 1.8383]], grad_fn=<AddBackward0>) 

tensor([[0.7847, 1.7523, 2.0198, 0.4269, 2.0218],
        [1.0844, 0.4511, 1.8012, 2.1393, 0.4113],
        [1.9213, 1.0800, 2.3942, 1.4376, 1.5860],
        [1.5755, 1.7692, 2.2654, 1.9001, 2.1408],
        [3.2435, 1.5751, 1.6577, 2.1182, 1.9007]]) 
 tensor([[0.6400, 1.5476, 1.6804, 1.8539, 2.1181],
        [1.8282, 0.4681, 1.8620, 2.1057, 0.4247],
        [1.6903, 1.4435, 2.4178, 1.6184, 2.1348],
        [0.9674, 1.2904, 2.4409, 1.8601, 1.8815],
        [3.2606, 1.3758, 1.0243, 1.9209, 1.8599]]) 
 tensor([[0.9413, 1.7720, 1.5788, 0.4510, 2.0158],
        [0.9930, 1.8593, 1.6466, 2.0043, 1.7540],
        [1.6214, 1.1438, 2.3507, 1.8670, 1.6166],
        [1.1119, 1.4717, 2.3585, 2.2579, 1.8321],
        [3.2381, 

In [18]:
# Реализуйте функцию MSE (Mean Squared Error):
# MSE = (1/n) * Σ(y_pred - y_true)^2
# где y_pred = w * x + b (линейная функция)
# Найдите градиенты по w и b
x = torch.rand((5,5))
y_true = torch.rand((5,5))
w = torch.rand((5,5),requires_grad=True)
b = torch.rand((5,5),requires_grad=True)
y_pred = w * x + b
MSE = (1/y.shape[0]) * torch.sum(y_pred - y_true) ** 2
MSE.backward()
print(w.grad,"\n",b.grad)

tensor([[0.3098, 1.0546, 0.5118, 0.4983, 0.6740],
        [0.6347, 0.8164, 0.3029, 1.0540, 0.0811],
        [1.0865, 0.9284, 0.1233, 0.6951, 0.8310],
        [0.1923, 0.4115, 0.7330, 0.3630, 0.6063],
        [0.8196, 0.7571, 0.8541, 0.5454, 0.6767]]) 
 tensor([[1.1807, 1.1807, 1.1807, 1.1807, 1.1807],
        [1.1807, 1.1807, 1.1807, 1.1807, 1.1807],
        [1.1807, 1.1807, 1.1807, 1.1807, 1.1807],
        [1.1807, 1.1807, 1.1807, 1.1807, 1.1807],
        [1.1807, 1.1807, 1.1807, 1.1807, 1.1807]])


In [39]:
# Реализуйте составную функцию: f(x) = sin(x^2 + 1)
# Найдите градиент df/dx
# Проверьте результат с помощью torch.autograd.grad
x = torch.rand((5,5),requires_grad=True)
f = torch.sin(x**2 + 1)
z = f.sum()
z.backward()
print(x.grad)
f = torch.sin(x**2 + 1)
z = f.sum()
torch.autograd.grad(z,x,create_graph=True)

tensor([[ 0.1327,  0.3034,  0.2069,  0.3216,  0.0924],
        [ 0.2736, -0.0703,  0.2407, -0.2272,  0.3028],
        [ 0.2944,  0.2216,  0.0901,  0.3036, -0.0296],
        [ 0.0361,  0.3104,  0.2127,  0.1914,  0.3193],
        [ 0.2512,  0.2756, -0.1099,  0.0962,  0.0936]])


(tensor([[ 0.1327,  0.3034,  0.2069,  0.3216,  0.0924],
         [ 0.2736, -0.0703,  0.2407, -0.2272,  0.3028],
         [ 0.2944,  0.2216,  0.0901,  0.3036, -0.0296],
         [ 0.0361,  0.3104,  0.2127,  0.1914,  0.3193],
         [ 0.2512,  0.2756, -0.1099,  0.0962,  0.0936]], grad_fn=<MulBackward0>),)